### ISSUE TITLE
calculator bug

### ISSUE THREAD

**Issue by Primly** [manu354/cryptocurrency-arbitrage#14]
I went to the hosted site today and it seems to have a bug in the calculation. It's telling me to trade 

```
TRANSFER BSTY FROM BLEUTRADE TO CRYPTOPIA (15.56%)
BSTY
15.56%
Bleutrade: 0.00617  Cryptopia: 0.00713
```
 then

```
SELL FOR BITB AND TRANSFER BACK TO CRYPTOPIA (4.71%)
BITB
4.71%
Bleutrade: 0.000890  Cryptopia: 0.000850
```

obviously this trade makes zero sense and it seems all the trades available have the same issue. Seems like we've broken something in the calculation. Or could this be related to memory leak issues?

**Comment by manu354** [comment]
Hey sorry at some point I swapped the market names around. I really should make the frontend a bit easier to work with.

**Comment by Primly** [comment]
ahhh ok, that makes more sense LOL
