### ISSUE TITLE
Price for exchanges seems swapped

### ISSUE THREAD

**Issue by tomglynch** [manu354/cryptocurrency-arbitrage#18]
Hi,

In the image below, the price for the first line is:
Bittrex: 0.144mBTC  
Poloniex: 0.152mBTC

and the price for the second line is the opposite:
Poloniex: 0.144mBTC 
Bittrex: 0.152mBTC

![image](https://user-images.githubusercontent.com/17879963/29016911-be0ed156-7b97-11e7-9f24-2c45c1c68c49.png)

I assume it's pulling the prices incorrectly. I haven't had a look yet at the source code but am willing to help out. 

Love the idea and the look of the site Manu,

Tom

**Comment by manu354** [comment]
Fixing in next commit.
