### ISSUE TITLE
Can't run front-end user interface locally

### ISSUE THREAD

**Issue by bush** [manu354/cryptocurrency-arbitrage#19]
I am trying serve the index.html page from the docs directory to run the same UI that is run at http://cryptoworks.co.  Does anyone know how to run the UI locally?

**Comment by manu354** [comment]
You have to remove the external URL that socket.io connects to, so it defaults to connecting to localhost. It's a line somewhere in ```script.js``` ```socket = io(''https://....")``` remove the link so its just ```... io()``` if you can't find it I will provide more info.

**Comment by bush** [comment]
Thanks!  That did the trick.
