### ISSUE TITLE
Jubi/BTC38 Exchanges are infeasible

### ISSUE THREAD

**Issue by gilrosenthal** [manu354/cryptocurrency-arbitrage#2]
I know that the program converts CNY to BTC for value, but ATM it would be very hard to actually try and do these trades because 

1. Jubi is in Chinese, and not sure about others but I certainly don't speak Mandarin 😆 
2. BTC38 has very little Alt/BTC pairs, so one would have to settle for CNY
2. Once you make the transaction, you have CNY, and I'm not quite sure what to do with that

Just some thoughts, let me know!

**Comment by Primly** [comment]
Agree! Trading on Chinese exchanges gives me the willies anyway.

**Comment by manu354** [comment]
Agree somewhat as well, usually more of a pain to do arbitrage with these exchanges than profit. But I actually have traded between btc38 and jubi successfully. In the next version the frontend will automatically not follow those markets ( "uncheck" them from the list)  and require to be manually checked to see the results. Then only people who care about those exchanges will see them.

**Comment by manu354** [comment]
Jubi and btc38 are now automatically not followed. Closing.
