### ISSUE TITLE
Issue when starting

### ISSUE THREAD

**Issue by amolc** [manu354/cryptocurrency-arbitrage#20]
main-1 (err):     at tryModuleLoad (module.js:446:12)
main-1 (err):     at Function.Module._load (module.js:438:3)
main-1 (err):     at Module.runMain (module.js:604:10)
main-1 (err):     at run (bootstrap_node.js:394:7)
main-1 (err):     at startup (bootstrap_node.js:149:9)
main-1 (err):     at bootstrap_node.js:509:3
main-1 (err): /Users/amol/projects/cryptocurrency-arbitrage/main.js:73
main-1 (err): async function computePrices(data) {
main-1 (err):       ^^^^^^^^
main-1 (err): SyntaxError: Unexpected token function
main-1 (err):     at Object.exports.runInThisContext (vm.js:76:16)
main-1 (err):     at Module._compile (module.js:542:28)
main-1 (err):     at Object.Module._extensions..js (module.js:579:10)
main-1 (err):     at Module.load (module.js:487:32)
main-1 (err):     at tryModuleLoad (module.js:446:12)
main-1 (err):     at Function.Module._load (module.js:438:3)
main-1 (err):     at Module.runMain (module.js:604:10)
main-1 (err):     at run (bootstrap_node.js:394:7)
main-1 (err):     at startup (bootstrap_node.js:149:9)
main-1 (err):     at bootstrap_node.js:509:3

**Comment by manu354** [comment]
Are you running node.js v8.00+

**Comment by manu354** [comment]
Are you also running the latest commit?

**Comment by manu354** [comment]
Can confirm this is because of not using node.js v8+. Closing.
