### ISSUE TITLE
Loads infinitely due to requests failing

### ISSUE THREAD

**Issue by tomglynch** [manu354/cryptocurrency-arbitrage#23]
cryptoworks.co loads infinitely, all requests like this fail: https://cryptoworks.co/socket.io/?EIO=3&transport=polling&t=LtenT5Y

Tested in both chrome and safari.

See here:

![image](https://user-images.githubusercontent.com/17879963/29344319-46bbb5b2-827a-11e7-9ad7-0b4e8c45a60b.png)

**Comment by manu354** [comment]
I still haven't activated the new hosting. You would have to run it locally for now.

**Comment by manu354** [comment]
It's currently set up for local production so just npm start.

**Comment by tomglynch** [comment]
Ah all good. Feel free to close
