### ISSUE TITLE
Error: cryptocurrency-arbitrage@1.4.0 start: `node main`

### ISSUE THREAD

**Issue by wimg** [manu354/cryptocurrency-arbitrage#30]
When running npm start, this is the output log :

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cryptocurrency-arbitrage@1.4.0~prestart: cryptocurrency-arbitrage@1.4.0
6 silly lifecycle cryptocurrency-arbitrage@1.4.0~prestart: no script for prestart, continuing
7 info lifecycle cryptocurrency-arbitrage@1.4.0~start: cryptocurrency-arbitrage@1.4.0
8 verbose lifecycle cryptocurrency-arbitrage@1.4.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle cryptocurrency-arbitrage@1.4.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/cryptocurrency-arbitrage/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin
10 verbose lifecycle cryptocurrency-arbitrage@1.4.0~start: CWD: /root/cryptocurrency-arbitrage
11 silly lifecycle cryptocurrency-arbitrage@1.4.0~start: Args: [ '-c', 'node main' ]
12 silly lifecycle cryptocurrency-arbitrage@1.4.0~start: Returned: code: 1  signal: null
13 info lifecycle cryptocurrency-arbitrage@1.4.0~start: Failed to exec start script
14 verbose stack Error: cryptocurrency-arbitrage@1.4.0 start: `node main`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid cryptocurrency-arbitrage@1.4.0
16 verbose cwd /root/cryptocurrency-arbitrage
17 error Linux 3.10.0-514.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error cryptocurrency-arbitrage@1.4.0 start: `node main`
22 error Exit status 1
23 error Failed at the cryptocurrency-arbitrage@1.4.0 start script 'node main'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the cryptocurrency-arbitrage package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node main
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs cryptocurrency-arbitrage
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls cryptocurrency-arbitrage
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by manu354** [comment]
Hey sorry for the delay. `19 error node v6.11.3` that line means that you are running node.js v6. This program only runs on node.js v8.0.0+
