### ISSUE TITLE
Repository Maintenance

### ISSUE THREAD

**Issue by ruidazeng** [manu354/cryptocurrency-arbitrage#49]
Is this repo still being actively maintained? Will issues and pull requested be handled? The last push was 7 years ago.

**Comment by adlai** [comment]
This [notice](https://github.com/manu354/cryptocurrency-arbitrage#notice) might have slipped past you, it's buried in the long document:

> I am now only focusing on the trading bot. Unfortunately I am going to keep that code private, and will not have time to work on this public version. _Feel free to still make pull requests_ - I will still take a look at any issues when they pop up.

I added emphasis to the important bit!
