### ISSUE TITLE
Option to manually remove a price difference pair

### ISSUE THREAD

**Issue by renrichie** [manu354/cryptocurrency-arbitrage#5]
The trading of some cryptocurrencies is paused on some websites, so some invalid trade opportunities are generated based on old data, e.g., UNB: Cryptopia -> Bittrex. It would be useful to have an option to manually remove a pairing from the listing.

**Comment by manu354** [comment]
You already can? You might have the website cached. Remove cache and try again. You can click on the check boxes to manually remove a pair.

**Comment by renrichie** [comment]
That removes the entire coin pairing, doesn't it? What I mean is perhaps the opportunity for arbitrage is valid on one website but not on another for that specific pairing. For example, UNB is currently paused on Cryptopia, but maybe there exists a pairing between Bittrex and Kraken. Unticking 'UNB' removes all possible pairings, and unticking 'Cryptopia' would remove all other pairings for other coins using Cryptopia.

**Comment by manu354** [comment]
Oh okay I understand. Will add to next commit.
