### ISSUE TITLE
Zero or Negative profits showing

### ISSUE THREAD

**Issue by procmail** [manu354/cryptocurrency-arbitrage#9]
Examples:
TOTAL PROFIT: -1.15%

- TRANSFER BTC FROM JUBI TO BTC38 (0.00%)
- SELL FOR ETH AND TRANSFER BACK TO JUBI (-1.15%)

**Comment by manu354** [comment]
BTC showing 0.00% is because of issue #3 

-1.15 is the correct functionality of the script. It shows the best trade to get back to the initial exchange with the least amount of loss, in most cases even profit. Here there is nothing with a lower loss than -1.1.5%

Closing
